# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - './genki.gemspec'

Lint/Eval:
  Exclude:
    - 'spec/support/capture.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/genki.rb'
