language: ruby
rvm:
  - 2.2.2
  - 2.2.4
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install: gem install bundler -v 1.11.2
notifications:
  email: false
  slack:
    secure: eGCFU2I8/LIeCuo6cWBatBoLwL8+eDRlcJJH194pMr12S4qkE7mDMeaRUhMvxruZGo/mzvbKzXBJ9SXo8Yyaa4q7DlRH8c4MijIE2VcCNNYeEDp1VC4su/alpEWtxatXNXlc+ZiRAFRvCADjrPXLmeFPhCP20nlfNrX8z6z8Iew/Jzh07GWyyXNIIz83lw/O6PFHNWudEugYpnQf1Z8QnIC18o2l5JKEJIa6W++EJ9Wi9MCBHVQdTNodb4TLVdbKJDtZxUOdTzkPblEVjnFTZQUhuX+NzwVxTdlyonUPypBGqFEhjTbYuxHQawRkfRM1QlLewynvzo+QR2D03EX5tKyqDuUmd4ISoNuKNmXxHuEYLDJJcLiJaL7oae02CYZe3Oayw0AYrhZBWKyfiMN7eFeQN4IG05ox0z1zJ3hy/Il/uWUIuQUp1ai2DnSqnG+fOwV9ivrv1YDA4XX3EIA3FxbU8EsZc9aQBIzIFFrBzwO2u0+Yy/M465n5/EL6R/FA6xIrKmNqcV7ZuXUdfqpsxtA82AG4M1mFps5UVs8roSFfe0nTPPHtL5NANmUbM5TuJS9ZbtOmClRf6jNAiTn9N2iAe9U2SL8b9MKJZTlvReNN6mt21DogKpsvas6uOIhigEu4m07iqtc89gyzWP8RPwM8EZhpr2nsAOMOtSHRPP0=
